name: "CloudFormation Deploy Action"
author: "jbw"
description: "Deploys a CloudFormation stack"

inputs:
  message:
    description: "The name of the stack to deploy"
    required: true
    default: "Hello"

runs:
  using: node16
  main: dist/index.js

branding:
  icon: zap
  color: yellow
