name: 'CloudFormation Deploy Action'
author: 'jbw'
description: 'Deploys a CloudFormation stack'

inputs:
  stackName:
    description: 'The name of the stack to deploy'
    required: true
    default: ''

runs:
  using: node16
  main: dist/index.js

branding:
  icon: zap
  color: yellow
