name: 'Test'
on:
  pull_request:
  push:
    branches:
      - main
      - next
      - alpha

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          npm install --immutable
          npm run test

      - name: Test Action
        id: test_action
        uses: ./
        with:
          stackName: 'test-stack'
          templateFile: './test/test-template.yml'
          capabilities: 'CAPABILITY_IAM'
          timeout: 60
          wait: true
          executeChangeSet: true
          enableRollback: false
          terminationProtection: false

      - name: Output
        run: echo ${{steps.test_action.outputs.stackId}}
