name: 'Test'
on:
  pull_request:
  push:
    branches:
      - main
      - next
      - alpha

jobs:
  # add localstack

  test:
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
          - 4571:4571

    env:
      LOCALSTACK_URL: http://localhost:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_DEFAULT_REGION: us-east-1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Action
        id: test_action
        env:
          LOCALSTACK_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_DEFAULT_REGION: us-east-1
        uses: ./
        with:
          stackName: 'test-stack'
          templateFile: 'test/test-template.json'
          capabilities: 'CAPABILITY_IAM'
          timeout: 60
          wait: true
          executeChangeSet: true
          enableRollback: false
          terminationProtection: false

      # - name: Run unit tests
      #   run: |
      #     npm install --immutable
      #     npm run test

      - name: Output
        run: echo ${{steps.test_action.outputs.stackId}}
